sudo: required
dist: trusty
language: node_js
node_js:
  - 'lts/*'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add angular-cli

cache: yarn

before_script:
- yarn
- yarn build:prod

script: yarn test:prod
